### ISSUE TITLE
Problem to dowload weights and with aromatics/symmetric compounds

### ISSUE THREAD

**Issue by orli91** [tiejundong/FlexPose#6]
Thanks for the work!

I tried to download the weights for local execution, but both at command line
and direct download the speed is slow (< 160 Kb/s) and fails at around 80%.

When trying the web server version, I noticed that aromatics and double-bonded in non-protein compounds tend
often to violate (more or less) co-planar constraints (could be a small setting for minimization in the web server?),
which is not happening in other systems such as DiffDock.
Moreover, big problems occurs when docking symmetric compounds that have multi-aromatics (see the attached example).
Atoms did not stay in place, as it seems that during inference the system cannot distinguish the aromatic ring to which each atom belongs to, and final things result messed up.
Thanks for any support!

Marco

[Input_and_server_output.zip](https://github.com/tiejundong/FlexPose/files/13693009/Input_and_server_output.zip)

**Comment by tiejundong** [comment]
Thanks for your attention to our work. 

- You can download parameters [here](https://1drv.ms/u/c/469b767efa9cca5a/EWWl7q0ZtCpEvAHBqyvK5jsBAo109EquswbYq9Z6lkwmWw).
- The energy minimization improves the geometric correctness of local structures, e.g., aromatics/symmetric parts. If the local structure is not correct, one may consider the following: 1. enhancing energy minimization (set `min_loop=100` or set `min_type='LBFGS'`). 2. decreasing constraint energy minimizion constant (set `min_constraint=0`). 3. Failed energy minimization in rare cases (i.e. failed to extract force field parameters in preprocessing). Although minimizing energy can improve local structural correctness, it cannot be expected to be utilized to improve accuracy as mentioned in our article and a recent study (Zhang, Xujun, et al. Nature Computational Science 3.9 (2023): 789-804.), especially for the highly flexible polymer-like ligand you provided, which is more challenging (Wang, Zhe, et al. Physical Chemistry Chemical Physics 18.18 (2016): 12964-12975.).

**Comment by xqh19970407** [comment]
i got a error,can you help me?


`==================== Running FlexPose ====================
2023-12-20 17:51:09,278 ERROR services.py:1363 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-12-20 17:51:09,278 ERROR services.py:1364 -- Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Traceback (most recent call last):
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/ray/_private/services.py", line 1350, in start_dashboard
    raise Exception(err_msg + last_log_str)
Exception: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-12-20 17:51:09,582 INFO worker.py:1518 -- Started a local Ray instance.
[2023-12-20 17:51:39,874 E 132336 132336] core_worker.cc:149: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory`

**Comment by xqh19970407** [comment]
i got an error, can you help me?



==================== Running FlexPose ====================
2023-12-20 17:51:09,278 ERROR services.py:1363 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-12-20 17:51:09,278 ERROR services.py:1364 -- Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Traceback (most recent call last):
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/ray/_private/services.py", line 1350, in start_dashboard
    raise Exception(err_msg + last_log_str)
Exception: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-12-20_17-51-06_723181_132336/logs/dashboard.log:
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/home/xiaoqi/miniconda3/envs/diffdock2/lib/python3.8/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
2023-12-20 17:51:09,582 INFO worker.py:1518 -- Started a local Ray instance.
[2023-12-20 17:51:39,874 E 132336 132336] core_worker.cc:149: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory

**Comment by tiejundong** [comment]
You can try setting `prepare_data_with_multi_cpu` to `False` to avoid processing by `ray`.

Besides, please do not raise irrelevant issues in other people's comments.
